const Position = require('../models/Position');

const defaultPositions = [
  {
    title: 'Web Development – Intern',
    type: 'Intern',
    category: 'Development',
    desc: 'Perfect opportunity for fresh graduates or students to gain hands-on experience in web development. Work on real projects and build your portfolio.',
    skills: ['HTML/CSS/JS', 'React basics', 'Git'],
    responsibilities: ['Build responsive web pages', 'Participate in code reviews', 'Write clean, documented code'],
    exp: 'Fresher / 0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Intern – Data Analytics',
    type: 'Intern',
    category: 'Analytics',
    desc: 'An opportunity for students to explore the field of data analytics. Build dashboards, analyze data, and gain insights into the top data tools.',
    skills: ['Excel / Google Sheets', 'SQL basics', 'Python (pandas)'],
    responsibilities: ['Analyze datasets', 'Create visual dashboards', 'Support data reporting'],
    exp: 'Fresher',
    location: 'Ahmedabad (Hybrid)',
    isActive: true,
  },
  {
    title: 'Intern – Data Science',
    type: 'Intern',
    category: 'Data science',
    desc: 'Ideal for students who want to explore data science, machine learning, and AI. Work on real datasets and build predictive models.',
    skills: ['Python', 'NumPy / Pandas', 'ML basics'],
    responsibilities: ['Design and train ML models', 'Perform data cleaning', 'Present findings to the team'],
    exp: 'Fresher',
    location: 'Ahmedabad (Hybrid)',
    isActive: true,
  },
  {
    title: 'Intern – AI/ML',
    type: 'Intern',
    category: 'Artificial Intelligence',
    desc: 'Perfect for fresh graduates to join our AI team and work on cutting-edge projects. Gain hands-on experience with real-world AI applications.',
    skills: ['Python', 'TensorFlow / PyTorch', '0–1 yr experience'],
    responsibilities: ['Implement AI/ML models', 'Participate in model training', 'Collaborate with senior engineers'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Intern – Digital Marketing (SEO)',
    type: 'Intern',
    category: 'Marketing',
    desc: 'Perfect opportunity for fresh graduates to get started in digital marketing. No experience required — we provide full training.',
    skills: ['SEO basics', '0–1 yr experience', 'Content writing'],
    responsibilities: ['Keyword research', 'On-page SEO optimization', 'Content creation and publishing'],
    exp: 'Fresher',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Digital Marketing (SMM/SEO)',
    type: 'Full-time',
    category: 'Marketing',
    desc: 'Manage social media, run campaigns, and grow our online presence. Perfect for candidates with a passion for digital growth.',
    skills: ['SEO / SEM', '0–1 yr experience', 'Social media tools'],
    responsibilities: ['Manage social media accounts', 'Run paid ad campaigns', 'Track and report analytics'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Intern – Cyber Security',
    type: 'Intern',
    category: 'It/security',
    desc: 'Perfect opportunity for fresh graduates to gain hands-on experience in cyber security. Work on real-world security challenges.',
    skills: ['Networking basics', '0–1 yr experience', 'Linux fundamentals'],
    responsibilities: ['Assist in security audits', 'Monitor network activity', 'Create security reports'],
    exp: 'Fresher',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Cyber Security',
    type: 'Full-time',
    category: 'It/security',
    desc: 'Protect our infrastructure and client systems. Conduct vulnerability assessments and implement security protocols.',
    skills: ['Network security', '0–1 yr experience', 'SIEM tools'],
    responsibilities: ['Conduct vulnerability assessments', 'Implement security protocols', 'Respond to incidents'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Senior Full Stack Developer',
    type: 'Full-time',
    category: 'Development',
    desc: 'Build scalable full-stack applications and mentor junior developers. Lead architecture decisions for client projects.',
    skills: ['React / Node.js', '2+ yrs experience', 'MongoDB / PostgreSQL'],
    responsibilities: ['Architect and build full-stack apps', 'Mentor junior developers', 'Conduct code reviews'],
    exp: '2+ yrs',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'React Native Developer',
    type: 'Full-time',
    category: 'Mobile development',
    desc: 'Build cross-platform mobile apps for iOS and Android. Integrate third-party APIs and optimize app performance.',
    skills: ['React Native', '0–1 yr experience', 'REST APIs'],
    responsibilities: ['Build cross-platform mobile apps', 'Integrate third-party APIs', 'Optimize app performance'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'UI/UX Designer',
    type: 'Full-time',
    category: 'Design',
    desc: 'Create beautiful, user-friendly interfaces. Design wireframes, prototypes, and conduct user research.',
    skills: ['Figma / Adobe XD', '0–1 yr experience', 'Prototyping'],
    responsibilities: ['Design wireframes and prototypes', 'Conduct user research', 'Collaborate with developers'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'DevOps Engineer',
    type: 'Full-time',
    category: 'Infrastructure',
    desc: 'Manage CI/CD pipelines, cloud infrastructure, and deployments. Automate processes and monitor system health.',
    skills: ['Docker / Kubernetes', '0–1 yr experience', 'AWS / GCP'],
    responsibilities: ['Manage CI/CD pipelines', 'Monitor infrastructure', 'Automate deployment processes'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
  {
    title: 'Business Development Executive',
    type: 'Full-time',
    category: 'Sales',
    desc: 'Drive business growth by identifying and closing new opportunities. Build long-term client relationships.',
    skills: ['Communication', '0–1 yr experience', 'CRM tools'],
    responsibilities: ['Identify new business opportunities', 'Build client relationships', 'Achieve monthly sales targets'],
    exp: '0–1 yr',
    location: 'Ahmedabad (On-site)',
    isActive: true,
  },
];

async function seedPositions() {
  const count = await Position.countDocuments();
  if (count > 0) return; // already seeded — skip

  await Position.insertMany(defaultPositions);
  console.log(`Seeded ${defaultPositions.length} positions.`);
}

module.exports = { seedPositions };
